### ISSUE TITLE
上下左右无法正常识别

### ISSUE THREAD

**Issue by FZZkill** [PowerAngelXD/YoLang#5]
就像这样（上，下，左，右）
![图片](https://user-images.githubusercontent.com/76607157/194330558-93eab7dc-efbf-4dc1-87a6-94e3f9e72305.png)
离谱不？
我尝试过修补这个问题，（gnu的readline给我看麻了）然后就没修
希望可以修改此Bug

**Comment by PowerAngelXD** [comment]
感谢您的意见，已经解决了这个问题
